version: '3.8'

services:
  primevue_breeze_spa:
    build: .
    container_name: primevue_breeze_spa
    entrypoint: /bin/sh
    working_dir: /web
    volumes:
      - '.:/web'
    tty: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.primevue_breeze_spa.rule=Host(`vue-spa.breeze-api.localhost`)"
      - "traefik.http.services.primevue_breeze_spa.loadbalancer.server.port=${VITE_PORT}"
      # To use any domain, such as `primevue-breeze-spa.localhost` (not sharing the same top level domain of the API):
      # Remove SESSION_DOMAIN env and add domain to SANCTUM_STATEFUL_DOMAINS env in Laravel API project
      # Update src/utils/axios.js baseURL property, or VITE_API_BASE_URL env to '/backend'
      #- "traefik.http.middlewares.backend-strip-prefix.stripprefix.prefixes=/backend"
      #- "traefik.http.routers.primevue_breeze_spa-backend.rule=Host(`primevue-breeze-spa.localhost`) && PathPrefix(`/backend`)"
      #- "traefik.http.routers.primevue_breeze_spa-backend.middlewares=backend-strip-prefix"
      #- "traefik.http.routers.primevue_breeze_spa-backend.service=breeze_api"
    networks:
      - proxy

networks:
  proxy:
    name: "traefik_network"
    external: true
