version: '3.8'

services:
  primevue_breeze_spa:
    build: .
    container_name: primevue_breeze_spa
    entrypoint: /bin/sh
    working_dir: /web
    volumes:
      - '.:/web'
    tty: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.primevue_breeze_spa.rule=Host(`vue-spa.breeze-api.localhost`)"
      - "traefik.http.services.primevue_breeze_spa.loadbalancer.server.port=${TRAEFIK_PORT}"
    networks:
      - proxy

networks:
  proxy:
    name: "traefik_network"
    external: true
